spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  security:
    user:
      name: rikka
      password: rikka
logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
taco:
  orders:
    pageSize: 10
