spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api
logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
taco:
  orders:
    pageSize: 10
